spring:
  application:
    name: Aether
    version: 0.0.1-beta
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  # OpenAI配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your_api_key_here}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      model: gpt-3.5-turbo

server:
  servlet:
    context-path: /api
    
# Aether机器人配置
aether:
  admin:
    # 管理员QQ列表，多个QQ号用逗号分隔
    qq-list:
      - "123456789" # 替换为实际管理员QQ号 